version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: echo $MILMOVE_DOCKERHUB_PAT_2023 | docker login -u $DOCKER_USER --password-stdin

      - run:
          name: Build containers
          command: make build

      - run:
          name: Test containers
          command: make test

      - run:
          name: Release container
          command: |
            shopt -s extglob
            # latest
            docker tag  milmove/docker-mvn milmove/docker-mvn:latest
            docker push milmove/docker-mvn:latest
workflows:
  version: 2
  build-containers:
    jobs:
      - build