#!/usr/bin/env bash
set -x -eu -o pipefail

# bust cache for apt-get daily
CACHE_APT=$(date '+%Y-%m-%d')

docker build --build-arg CACHE_APT="$CACHE_APT" \
	     --build-arg CACHE_PIP="$CACHE_PIP" \
	     -t trussworks/docker-template \
	     .