#!/bin/bash
set -exu -o pipefail

function test_latest() {
  tag=latest
  echo "Testing ${tag} Dockerfile"

  docker run -it "milmove/docker-mvn:${tag}" shellcheck --version
  docker run -it "milmove/docker-mvn:${tag}" circleci version
  docker run -it "milmove/docker-mvn:${tag}" aws --version
  docker run -it "milmove/docker-mvn:${tag}" gh --version
  docker run -it "milmove/docker-mvn:${tag}" mvn --version

  echo "Passed ${tag}"
}

# if doing multiple tags
# for tag in latest; do
#     echo "* Testing USER is properly set to 'circleci' on '$tag' tagged image"
#     docker run -it milmove/docker-mvn:$tag bash -xc '[[ $(whoami) = circleci ]]'

#     case ${tag} in
#         latest)
#         test_latest
#         ;;
# esac

#done

tag=latest
echo "* Testing USER is properly set to 'circleci' on '${tag}' tagged image"
docker run -it milmove/docker-mvn:$tag bash -xc '[[ $(whoami) = circleci ]]'
test_latest

echo Passed.
exit 0