#!/bin/bash
set -eu -o pipefail

for tag in latest; do
    echo "* Testing USER is properly set to 'circleci' on '$tag' tagged image"
    docker run -it trussworks/docker-template:$tag bash -xc '[[ $(whoami) = circleci ]]'
done

echo Passed.
exit 0